spring:
  application:
    name: study-hard
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
    vectorstore:
      qdrant:
        collection-name: study-hard
        port: 6334
        initialize-schema: true
        host: localhost
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-hard
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: chaudiensdk5@gmail.com
    password: qylk wodv lcfw ifnh
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090
jwt:
  credentials:
    secretKey: cd1a4405ed4c987cde177f55c62ba23e085337259e7b659b792a8447a0b28985a36496137ea82f5f017d9da29f7ba5d9eaa67f82a6b91c30bd5a45a153b29cd7
    timeLiveAccessToken: 3600
    timeLiveRefreshToken: 108300
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
qdrant:
  init-data: false
openapi:
  oauth2:
    basic-auth:
      authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
      tokenUrl: https://oauth2.googleapis.com/token
springdoc:
  swagger-ui:
    oauth:
      use-basic-authentication-with-access-code-grant: true
      client-id: 73964980113-nifujb8sqn1219jul7padl4h8kf0f2go.apps.googleusercontent.com
      client-secret: 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
      scopes:
    oauth2-redirect-url: http://localhost:8090/swagger-ui/oauth2-redirect.html
