spring:
  application:
    name: study-hard
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-hard
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${MAIL_USERNAME}
    password:  ${MAIL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8090
jwt:
  credentials:
    secretKey: ${JWT_SECRET_KEY}
    timeLiveAccessToken: 3600
    timeLiveRefreshToken: 108300
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
qdrant:
  init-data: false
openapi:
  oauth2:
    basic-auth:
      authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
      tokenUrl: https://oauth2.googleapis.com/token
springdoc:
  swagger-ui:
    oauth:
      use-basic-authentication-with-access-code-grant: true
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      scopes:
    oauth2-redirect-url: http://localhost:8090/swagger-ui/oauth2-redirect.html
swagger:
  credentials:
    basic-auth:
        accounts:
          - email: ${EMAIL_ACCESS_SWAGGER}
            password: ${PASSWORD_ACCESS_SWAGGER}
          - email: ${EMAIL_ACCESS_SWAGGER_2}
            password: ${PASSWORD_ACCESS_SWAGGER_2}
          - email: ${EMAIL_ACCESS_SWAGGER_3}
            password: ${PASSWORD_ACCESS_SWAGGER_3}
